### ISSUE TITLE
logstream does not work with ruby < 2.1.2

### ISSUE THREAD

**Issue by timhilliard** [acquia/logstream#12]
looks to be an issue with faye-websocket but not totally sure.

```
$ logstream tail prod:testsite prodlive --debug
-> connect to wss://logstream.acquia.com/ah_websocket/logstream/v1
/Users/timhilliard/.rvm/gems/ruby-2.1.1/gems/websocket-driver-0.4.0/lib/websocket/driver/event_emitter.rb:36:in `listener_count': undefined method `has_key?' for nil:NilClass (NoMethodError)
    from /Users/timhilliard/.rvm/gems/ruby-2.1.1/gems/faye-websocket-0.7.5/lib/faye/websocket/api/event_target.rb:36:in `dispatch_event'
    from /Users/timhilliard/.rvm/gems/ruby-2.1.1/gems/faye-websocket-0.7.5/lib/faye/websocket/client.rb:32:in `rescue in initialize'
    from /Users/timhilliard/.rvm/gems/ruby-2.1.1/gems/faye-websocket-0.7.5/lib/faye/websocket/client.rb:10:in `initialize'
    from /Users/timhilliard/.rvm/gems/ruby-2.1.1/gems/logstream-0.0.4/lib/logstream/client.rb:45:in `new'
    from /Users/timhilliard/.rvm/gems/ruby-2.1.1/gems/logstream-0.0.4/lib/logstream/client.rb:45:in `block in run'
    from /Users/timhilliard/.rvm/gems/ruby-2.1.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `call'
    from /Users/timhilliard/.rvm/gems/ruby-2.1.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
    from /Users/timhilliard/.rvm/gems/ruby-2.1.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
    from /Users/timhilliard/.rvm/gems/ruby-2.1.1/gems/logstream-0.0.4/lib/logstream/client.rb:43:in `run'
    from /Users/timhilliard/.rvm/gems/ruby-2.1.1/gems/logstream-0.0.4/bin/logstream:79:in `tail'
    from /Users/timhilliard/.rvm/gems/ruby-2.1.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/timhilliard/.rvm/gems/ruby-2.1.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/timhilliard/.rvm/gems/ruby-2.1.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Users/timhilliard/.rvm/gems/ruby-2.1.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/timhilliard/.rvm/gems/ruby-2.1.1/gems/logstream-0.0.4/bin/logstream:88:in `<top (required)>'
    from /Users/timhilliard/.rvm/gems/ruby-2.1.1/bin/logstream:23:in `load'
    from /Users/timhilliard/.rvm/gems/ruby-2.1.1/bin/logstream:23:in `<main>'
    from /Users/timhilliard/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
    from /Users/timhilliard/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
```

I tested this against 1.9.1, 1.9.3, 2.0.0, 2.1.0, 2.1.1 which all failed in the same way. 2.1.2 and upwards were fine.
